### ISSUE TITLE
No module named Pathos

### ISSUE THREAD

**Issue by joeymizrahi** [tzuhsial/edgar-10k-mda#2]
when running the second comment you put in the README: 

> python form10k.py --index_path ./year2016-2016.10k.index --txt_dir ./data/txt

I get the following error:

> Traceback (most recent call last):
  File "form10k.py", line 11, in <module>
    from pathos.pools import ProcessPool
ModuleNotFoundError: No module named 'pathos'

I tried importing pathos o a different project and it did work

**Comment by tzuhsial** [comment]
Hi
The same command works for me.
My environment setup is
```bash
#python3.5
pip install -r requirements.txt
```

**Comment by joeymizrahi** [comment]
I installed all requirements and still get the issue

**Comment by tzuhsial** [comment]
@cs4242 I believe the current information is insufficient to determine the cause. 
It is better if you can provide your environment configuration(system) and error messages

**Comment by joeymizrahi** [comment]
I have already posted the error
how can I post my configurations?

**Comment by tzuhsial** [comment]
@cs4242 I have an updated version without pathos(and multiprocessing), so I think this issue can be closed.
