### ISSUE TITLE
The code doesn't run completly.

### ISSUE THREAD

**Issue by formulli** [tzuhsial/edgar-10k-mda#5]
When I try to run the code it only creates a data folder with subfolders of form10k and index. form10k is an empty folder while the index folder has only 3 files shown in the attached screenshot.

![error 2](https://user-images.githubusercontent.com/54708160/76161547-3e635380-6156-11ea-95b9-b1f3519bacc7.PNG)

**Comment by tzuhsial** [comment]
@formulli 
This looks like intermediate results of the program.  The program takes some time to finish. Did you wait for the code to finish?

Also, can you please try running with the "--debug" flag again and show me the program execution results?
```bash
python edgar.py --start_year 2016 --end_year 2016 --quarters 1 2 --data_dir ./data/ --debug
```

**Comment by tzuhsial** [comment]
Closing as no reply

**Comment by formulli** [comment]
Hi Antonie.
Hope you are well.
The code has the same error. I run that debug flag but it has the
same error.

**Comment by formulli** [comment]
I waited for it to finish its execution and now also try that code of "debug". But its not helping me out.
