### ISSUE TITLE
Issue downloading the forms

### ISSUE THREAD

**Issue by thiagomar1nho** [tzuhsial/edgar-10k-mda#7]
Hello,

The program is running, it creates the .idx and fills the combined.csv properly, but when it should read the URLs and download the forms from the combined.csv it stop working.
![github](https://user-images.githubusercontent.com/84578490/119145668-29689c80-ba4a-11eb-8948-2eae9e49645e.JPG)

Thank you!

**Comment by tzuhsial** [comment]
Replied via email.   This looks like an empty line to me in the csv file.  Either the index download failed or is an malformed file.  

A if clause should be able to bypass this error.
`if len(row) == 0: continue `

**Comment by trungdo1501** [comment]
Hi,
Thank you for the given code but I experienced the same issue. Could you please help me to resolve it?
![image](https://user-images.githubusercontent.com/86206662/122687720-c36d6180-d20f-11eb-82bb-0178ca9ff1e7.png)
Thank you very much.

**Comment by tzuhsial** [comment]
Hey @trungdo1501, can you please paste your code modifications too?  Adding the if else clause I pasted above should by pass this error.

**Comment by tzuhsial** [comment]
Closed due to inactivity.
